[versions]
agp = "8.13.2"
icons = "1.1.0"
materialVersion = "1.5.0"
oneui-design = "1.2.6"
kotlin = "1.9.22"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.0"
material = "1.13.0"
constraintlayout = "2.2.0"
lifecycle = "2.8.0"
fragmentKtx = "1.8.0"
navigationFragmentKtx = "2.9.6"
navigationUiKtx = "2.9.6"
navigationFragment = "2.9.6"
runtime = "1.10.0"
ui = "1.10.0"
navigationUiKtxVersion = "2.9.6"
oneui-compose = "0.7.0"
composeBom = "2024.02.02"
composeCompiler = "1.5.10"
uiVersion = "1.10.0"
desugarJdkLibs = "2.1.5"
kotlinCoroutines = "1.8.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
sesl-icons = { module = "io.github.oneuiproject:icons", version.ref = "icons" }
oneuidesign = { module = "io.github.oneuiproject:design", version.ref = "oneui-design" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
sesl-material = { module = "io.github.oneuiproject.sesl:material", version.ref = "materialVersion" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
androidx-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "runtime" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtxVersion" }
oneui-compose = { group = "com.github.TrainerSnow", name = "oneui-compose", version.ref = "oneui-compose" }
androidx-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "uiVersion" }
desugar-jdk-libs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugarJdkLibs" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

